#!/bin/bash

path=`dirname $0`
cd $path

mkdir images

ip=`/sbin/ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"`

echo "Request Path: http://$ip:8000/images"

python run.py